## Generates horizontal plots of neighbourhood size (x-axis) and model-estimated NH parasite effect (+/-CIs) on y-axis
##  - Separate plot for each specified time window
##  - Eimeria species in separate plots side-by-side



## CLEAR MEMORY
rm(list = ls())



## READ IN RELEVANT STATS SUMMARY FILES (generated by 'run_statistical_analysis')
## EIM INTENSITY ~ NEMPREV PLOTS
#dat17.h <- read.csv("STATS - Ehung Int NHprev 17.csv", header=T)[,2:5]
#dat34.h <- read.csv("STATS - Ehung Int NHprev 34.csv", header=T)[,2:5]
#dat51.h <- read.csv("STATS - Ehung Int NHprev 51.csv", header=T)[,2:5]
#datall.h <- read.csv("STATS - Ehung Int NHprev all.csv", header=T)[,2:5]

#dat17.a <- read.csv("STATS - Eapp Int NHprev 17.csv", header=T)[,2:5]
#dat34.a <- read.csv("STATS - Eapp Int NHprev 34.csv", header=T)[,2:5]
#dat51.a <- read.csv("STATS - Eapp Int NHprev 51.csv", header=T)[,2:5]
#datall.a <- read.csv("STATS - Eapp Int NHprev all.csv", header=T)[,2:5]


## EIM INTENSITY ~ NEMMEANBURDEN PLOTS
#dat17.h <- read.csv("STATS - Ehung Int NHMeanburden 17.csv", header=T)[,2:5]
#dat34.h <- read.csv("STATS - Ehung Int NHMeanburden 34.csv", header=T)[,2:5]
#dat51.h <- read.csv("STATS - Ehung Int NHMeanburden 51.csv", header=T)[,2:5]
#datall.h <- read.csv("STATS - Ehung Int NHMeanburden all.csv", header=T)[,2:5]

#dat17.a <- read.csv("STATS - Eapp Int NHMeanburden 17.csv", header=T)[,2:5]
#dat34.a <- read.csv("STATS - Eapp Int NHMeanburden 34.csv", header=T)[,2:5]
#dat51.a <- read.csv("STATS - Eapp Int NHMeanburden 51.csv", header=T)[,2:5]
#datall.a <- read.csv("STATS - Eapp Int NHMeanburden all.csv", header=T)[,2:5]


## EIM BINOMIAL ~ NEMPREV PLOTS
#dat17.h <- read.csv("STATS - Ehung INF NHprev 17.csv", header=T)[,2:5]
#dat34.h <- read.csv("STATS - Ehung INF NHprev 34.csv", header=T)[,2:5]
#dat51.h <- read.csv("STATS - Ehung INF NHprev 51.csv", header=T)[,2:5]
#datall.h <- read.csv("STATS - Ehung INF NHprev all.csv", header=T)[,2:5]

#dat17.a <- read.csv("STATS - Eapp INF NHprev 17.csv", header=T)[,2:5]
#dat34.a <- read.csv("STATS - Eapp INF NHprev 34.csv", header=T)[,2:5]
#dat51.a <- read.csv("STATS - Eapp INF NHprev 51.csv", header=T)[,2:5]
#datall.a <- read.csv("STATS - Eapp INF NHprev all.csv", header=T)[,2:5]


## EIM BINOMIAL ~ NEMMEANBURDEN PLOTS
dat17.h <- read.csv("STATS - Ehung INF NHMeanburden 17.csv", header=T)[,2:5]
dat34.h <- read.csv("STATS - Ehung INF NHMeanburden 34.csv", header=T)[,2:5]
dat51.h <- read.csv("STATS - Ehung INF NHMeanburden 51.csv", header=T)[,2:5]
datall.h <- read.csv("STATS - Ehung INF NHMeanburden all.csv", header=T)[,2:5]

dat17.a <- read.csv("STATS - Eapp INF NHMeanburden 17.csv", header=T)[,2:5]
dat34.a <- read.csv("STATS - Eapp INF NHMeanburden 34.csv", header=T)[,2:5]
dat51.a <- read.csv("STATS - Eapp INF NHMeanburden 51.csv", header=T)[,2:5]
datall.a <- read.csv("STATS - Eapp INF NHMeanburden all.csv", header=T)[,2:5]





## FUNCTION TO COLOUR-CODE POINTS DEPENDING IF CIs CROSS ZERO
#   returns red (orange) if 'significant' or black (grey) if no
#   .h version for hungaryensis; .a version for Eapp
sigcheck2.h <- function(lwr, upr){
  return(ifelse(upr<=0 | lwr>=0, "red", "black"))
}

sigcheck2.a <- function(lwr, upr){
  return(ifelse(upr<=0 | lwr>=0, "orange", "grey"))
}



## DISTANCE LABELS (neighbourhood sizes)
dist <- c(10, 14.1, 20, 22.4, 28.3, 30, 31.6, 36.1, 40, 50)




## SELECT pdf NAME, DEPENDING ON RESPONSE AND NH PREDICTOR VARIABLES
#pdf("OUTPUT - Eimeria Intensity v NH Hpoly prev.pdf")
#pdf("OUTPUT - Eimeria Intensity v NH Hpoly mburden.pdf")
#pdf("OUTPUT - Eimeria PA v NH Hpoly prev.pdf")
pdf("OUTPUT - Eimeria PA v NH Hpoly mburden.pdf")



## SET MARGINS
par(oma=c(4,5,0,4)) #b, l , t , r 
par(mar=c(0.5,1,1.5,1)) #b, l , t , r
par(mfrow=c(4,2))


## FUNCTION TO CONSTRUCT PLOT FOR A SPECIFIED DATASET
#  Inputs: 'dat' = the dataset
#          'plotnum' - which of the 4 plots this is - determines axis labeling
plotfunc <- function(h.dat, a.dat, plotnum){

  #Extract relevant data to plot
  h.est <- (as.numeric(h.dat[,2]))
  h.lw <- (as.numeric(h.dat[,3]))
  h.up <- (as.numeric(h.dat[,4]))
  a.est <- (as.numeric(a.dat[,2]))
  a.lw <- (as.numeric(a.dat[,3]))
  a.up <- (as.numeric(a.dat[,4]))
  
  #Get the colour-coding, depending on if CIs overlap 0 or not
  h.cols <- apply(h.dat[,3:4], 1, function(x) sigcheck2.h(x[1],x[2]))
  a.cols <- apply(a.dat[,3:4], 1, function(x) sigcheck2.a(x[1],x[2]))
  
  #ylims:
    #EIM INTENSITY ~ NEM PREV LIMITS: ylim = c(-20,20)
    #EIM INTENSITY ~ NEM MeanBUR LIMITS: ylim = c(-4.5,4)
    #EIM P-A ~ NEM PREV LIMITS: ylim = c(-8,10)
    #EIM P-A ~ NEM MeanBUR LIMITS: ylim = c(-1,3)
    #Ylim <- c(-25,20) #Int ~ Prev
    #Ylim <- c(-4.5,4)  #Int ~ Mean burden
    #Ylim <- c(-8,10)  #PA ~ Prev
    Ylim <- c(-1,3)  #PA ~ Mean burden
  
  plot(dist, (as.numeric(h.est)) , type = "p",
     ylim = Ylim, axes = FALSE, xlab = "", ylab = "", main = "", col=h.cols, pch=16, cex=1.8)
  
  #Add Ehung arrows, from lw 95%CI to up 95%CI 
  arrows(x0 = (dist),
       y0 = h.lw,
       x1 = (dist),
       y1 = h.up,
       length=0.05, angle=90, lwd = 2, code=3, col=h.cols)
  
  #Add axes - only plot the axis labels for the last plot
  axis(2, las = 2, lwd = 1, cex.axis=1.1)
  ifelse(plotnum==4, distlabels <- seq(0, 50, by=10), distlabels <- F)
  axis(1, at=seq(0, 50, by=10), labels = distlabels, cex.axis=1.5)
  
  #Add horizontal line at 0
  abline(h = 0, lty = 2)
  
  
  #Add Eapp data
  plot(dist, (as.numeric(a.est)) , type = "p",
       ylim = Ylim, axes = FALSE, xlab = "", ylab = "", main = "", col=a.cols, pch=16, cex=1.8)
  
  #Add Eapp arrows, from lw 95%CI to up 95%CI 
  arrows(x0 = (dist),
         y0 = a.lw,
         x1 = (dist),
         y1 = a.up,
         length=0.05, angle=90, lwd = 2, code=3, col=a.cols)
  
  #Add axes - only plot the axis labels for the last plot
  axis(2, las = 2, lwd = 1, labels = F, cex.axis=1.1)
  ifelse(plotnum==4, distlabels <- seq(0, 50, by=10), distlabels <- F)
  axis(1, at=seq(0, 50, by=10), labels = distlabels, cex.axis=1.5)

  #Add horizontal line at 0
  abline(h = 0, lty = 2)
  
  }  #CLOSE plotfunc



## CALL plotfunc TO CREATE THE 4 PLOTS
plotfunc(dat17.h, dat17.a, 1)
plotfunc(dat34.h, dat34.a, 2)
plotfunc(dat51.h, dat51.a, 3)
plotfunc(datall.h, datall.a, 4)



## ADD X-AXIS LABEL
mtext("Neighbourhood size (m)", side=1, outer=T, las=1, line=2.5, cex=1.5)



## ADD COLUMN LABELS
mtext(expression(italic("E. hungaryensis")), side=3, outer=T, line=-2, adj=0.15, cex=1.3)
mtext(expression(italic("E. apionodes")), side=3, outer=T, line=-2, adj=0.8, cex=1.3)



## ADD TIME WINDOW LABELS
mtext("17 days", side=4, outer=T, line=0, adj=0.2, padj=-24, las=1)
mtext("34 days", side=4, outer=T, line=0, adj=0.2, padj=-10, las=1)
mtext("51 days", side=4, outer=T, line=0, adj=0.2, padj=4, las=1)
mtext("All days", side=4, outer=T, line=0, adj=0.2, padj=18, las=1)



## ADD Y-AXIS LABEL
#  Select as appropriate depending on Eimeria response variable and H polygyrus NH predictor variable 
#mtext(expression(paste("Effect of ", italic("H. polygyrus"), " NH prevalence on ", italic("Eimeria"), " intensity")), side=2, outer=T, las=3, line=2, cex=1.4)
#mtext(expression(paste("Effect of ", italic("H. polygyrus"), " NH mean burden on ", italic("Eimeria"), " intensity")), side=2, outer=T, las=3, line=2, cex=1.4)
#mtext(expression(paste("Effect of ", italic("H. polygyrus"), " NH prevalence on ", italic("Eimeria"), " P/A")), side=2, outer=T, las=3, line=2, cex=1.4)
mtext(expression(paste("Effect of ", italic("H. polygyrus"), " NH mean burden on ", italic("Eimeria"), " P/A")), side=2, outer=T, las=3, line=2, cex=1.4)

dev.off()
