# Generates horizontal plots of neighbourhood size (x-axis) and model-estimated NH prevalence effect (+/-CIs) on y-axis
#  for each specified time window

#Read in relevant summary files, generated by 'run_statistical_analysis'
dat17 <- read.csv("output/Eapp_hpol17 stats.csv", header=T)[,2:5]
dat34 <- read.csv("output/Eapp_hpol34 stats.csv", header=T)[,2:5]
dat51 <- read.csv("output/Eapp_hpol51 stats.csv", header=T)[,2:5]
datall <- read.csv("output/Eapp_hpolall stats.csv", header=T)[,2:5]


##Function to colour code points depending on if upper CI value <0 or lower CI value >0
#   returns red if 'sig' or black if not
sigcheck2 <- function(lwr, upr){
  return(ifelse(upr<=0 | lwr>=0, "red", "black"))
}


#Distance labels
dist <- c(10, 14.1, 20, 22.4, 28.3, 30, 31.6, 36.1, 40, 50)


##Create plot

pdf("Coinfection combined plot.pdf")

#Set margins
par(mar=c(1,1,2,1)) #b, l , t , r
par(oma=c(4,5,1,1))
par(mfrow=c(4,1))


## Function to construct plot for a specified dataset
## Inputs: 'dat' = the dataset
##         'mainlab' = the distance for that dataset, to be used as the 'main' plot label
##         'axlab' = boolean, whether to write the y-axis labels for the plot (only T for the first one)
plotfunc <- function(dat, mainlab, axlab){

  #Extract relevant data to plot
  est <- (as.numeric(dat[,2]))
  lw <- (as.numeric(dat[,3]))
  up <- (as.numeric(dat[,4]))
  
  #Get the colour-coding, depending on if upr CI overlaps 0 or not
  cols <- apply(dat[,3:4], 1, function(x) sigcheck2(x[1],x[2]))
  
  plot(dist, (as.numeric(est)) , type = "p",
     ylim = c(-20,20), axes = FALSE, xlab = "", ylab = "", main = "", col=cols, pch=16, cex=1.8)
  title(main = paste(mainlab, "Days\n", sep=" "), line=-1.2)
  
  #Add arrows, from lw 95%CI to up 95%CI 
  arrows(x0 = (dist),
       y0 = lw,
       x1 = (dist),
       y1 = up,
       length=0.05, angle=90, lwd = 3, code=3, col=cols)

  #Add axes - only plot the axis labels for the first plot
  distlabels <- seq(0, 50, by=10)
  if(!axlab) distlabels <- F
  axis(2, las = 2, lwd = 1)
  axis(1, at=seq(0, 50, by=10), labels = distlabels, cex.axis=0.9)

  #Add horizontal line at 0
  abline(h = 0, lty = 2)
  
  }  #CLOSE plotfunc


#Call plotfunc to create the 4 plots
plotfunc(dat17, 17, F)
plotfunc(dat34, 34, F)
plotfunc(dat51, 51, F)
plotfunc(datall, "All", T)


#Add a y-axis label
#mtext(expression(paste("Effect of ", italic("H. polygyrus"), " on ", italic("E. hungaryensis"))), side=2, outer=T, las=3, line=2, cex=1.5)
mtext(expression(paste("Effect of ", italic("H. polygyrus"), " on ", italic("E. apionodes"))), side=2, outer=T, las=3, line=2, cex=1.5)
mtext("Neighbourhood size", side=1, outer=T, las=1, line=2.5, cex=1.5)

dev.off()
