## Read in relevant data files and run brm analyses for each distance and specified time window
##  Output summary (estimates & upr/lwr CIs) to summary data files for storage and plotting 
##



## CLEAR MEMORY
rm(list = ls())



## LOAD DATA 
# Read in relevant datafiles as generated by 'execute.parasite.function'
# Select either Ehung or Eapp files as needed
#Eim_hpol17 <- read.csv("data output/DATA - Ehung_17.csv", header = T)
#Eim_hpol34 <- read.csv("data output/DATA - Ehung_34.csv", header = T)
#Eim_hpol51 <- read.csv("data output/DATA - Ehung_51.csv", header = T)
#Eim_hpolall <- read.csv("data output/DATA - Ehung_all.csv", header = T)
Eim_hpol17 <- read.csv("data output/DATA - Eapp_17.csv", header = T)
Eim_hpol34 <- read.csv("data output/DATA - Eapp_34.csv", header = T)
Eim_hpol51 <- read.csv("data output/DATA - Eapp_51.csv", header = T)
Eim_hpolall <- read.csv("data output/DATA - Eapp_all.csv", header = T)



## LOAD FUNCTIONS AND LIBRARIES
source("model.run.R")
library(brms)



## DISTANCE LABELS
dist <- c(10, 14.1, 20, 22.4, 28.3, 30, 31.6, 36.1, 40, 50)



## SET PRIORS
prior <- c(prior_string("normal(0,10)", class = "b"))



## SET RESPONSE AND EXPLANATORY PARASITE VARIABLES
#Specify Ehung or Eapp, Int (intensity; EPG) or INF (presence/absence) as needed
#Response.Parasite <- "EhungInt" 
#Response.Parasite <- "EappInt" 
#Response.Parasite <- "EhungINF" 
Response.Parasite <- "EappINF" 

Explanatory.Parasite <- "H. polygyrus"



## RUN MODELS
# var names for Nem Prev models
#var.names <- c("NemPrev_10", "NemPrev_14.1", "NemPrev_20", "NemPrev_22.4", "NemPrev_28.3", "NemPrev_30",
#               "NemPrev_31.6", "NemPrev_36.1", "NemPrev_40", "NemPrev_50")

# Var names for Nem mean burden (pre-logged) models
var.names <- c("NemMeanBurden_10", "NemMeanBurden_14.1", "NemMeanBurden_20", "NemMeanBurden_22.4", "NemMeanBurden_28.3", "NemMeanBurden_30",
               "NemMeanBurden_31.6", "NemMeanBurden_36.1", "NemMeanBurden_40", "NemMeanBurden_50")




## CARRY OUT ANALYSIS FOR EACH TIME WINDOW IN TURN
# Select either 'model.run.intensity.control' or 'model.run.bernoulli.control' depending on response variable type
model.data  <- Eim_hpol17
model.data$response.var <- model.data[, Response.Parasite]
#output.summary.17 <- model.run.intensity.control(model.data, var.names)
output.summary.17 <- model.run.bernoulli.control(model.data, var.names)

model.data  <- Eim_hpol34
model.data$response.var <- model.data[, Response.Parasite]
#output.summary.34 <- model.run.intensity.control(model.data, var.names)
output.summary.34 <- model.run.bernoulli.control(model.data, var.names)

model.data  <- Eim_hpol51
model.data$response.var <- model.data[, Response.Parasite]
#output.summary.51 <- model.run.intensity.control(model.data, var.names)
output.summary.51 <- model.run.bernoulli.control(model.data, var.names)

model.data  <- Eim_hpolall
model.data$response.var <- model.data[, Response.Parasite]
#output.summary.all <- model.run.intensity.control(model.data, var.names)
output.summary.all <- model.run.bernoulli.control(model.data, var.names)




## OUTPUT SUMMARY DATA FOR EACH TIME POINT
# Select options below depending on Eimeria species, Response type (Int or INF), NH predictor varaible (prevalence or meanburden)
#write.csv(output.summary.17, "stats output/STATS - Ehung Int NHprev 17.csv")
#write.csv(output.summary.34, "stats output/STATS - Ehung Int NHprev 34.csv")
#write.csv(output.summary.51, "stats output/STATS - Ehung Int NHprev 51.csv")
#write.csv(output.summary.all, "stats output/STATS - Ehung Int NHprev all.csv")

#write.csv(output.summary.17, "stats output/STATS - Eapp Int NHprev 17.csv")
#write.csv(output.summary.34, "stats output/STATS - Eapp Int NHprev 34.csv")
#write.csv(output.summary.51, "stats output/STATS - Eapp Int NHprev 51.csv")
#write.csv(output.summary.all, "stats output/STATS - Eapp Int NHprev all.csv")



#write.csv(output.summary.17, "stats output/STATS - Ehung Int NHMeanburden 17.csv")
#write.csv(output.summary.34, "stats output/STATS - Ehung Int NHMeanburden 34.csv")
#write.csv(output.summary.51, "stats output/STATS - Ehung Int NHMeanburden 51.csv")
#write.csv(output.summary.all, "stats output/STATS - Ehung Int NHMeanburden all.csv")

#write.csv(output.summary.17, "stats output/STATS - Eapp Int NHMeanburden 17.csv")
#write.csv(output.summary.34, "stats output/STATS - Eapp Int NHMeanburden 34.csv")
#write.csv(output.summary.51, "stats output/STATS - Eapp Int NHMeanburden 51.csv")
#write.csv(output.summary.all, "stats output/STATS - Eapp Int NHMeanburden all.csv")



#write.csv(output.summary.17, "stats output/STATS - Ehung INF NHprev 17.csv")
#write.csv(output.summary.34, "stats output/STATS - Ehung INF NHprev 34.csv")
#write.csv(output.summary.51, "stats output/STATS - Ehung INF NHprev 51.csv")
#write.csv(output.summary.all, "stats output/STATS - Ehung INF NHprev all.csv")

#write.csv(output.summary.17, "stats output/STATS - Eapp INF NHprev 17.csv")
#write.csv(output.summary.34, "stats output/STATS - Eapp INF NHprev 34.csv")
#write.csv(output.summary.51, "stats output/STATS - Eapp INF NHprev 51.csv")
#write.csv(output.summary.all, "stats output/STATS - Eapp INF NHprev all.csv")



#write.csv(output.summary.17, "stats output/STATS - Ehung INF NHMeanburden 17.csv")
#write.csv(output.summary.34, "stats output/STATS - Ehung INF NHMeanburden 34.csv")
#write.csv(output.summary.51, "stats output/STATS - Ehung INF NHMeanburden 51.csv")
#write.csv(output.summary.all, "stats output/STATS - Ehung INF NHMeanburden all.csv")

write.csv(output.summary.17, "stats output/STATS - Eapp INF NHMeanburden 17.csv")
write.csv(output.summary.34, "stats output/STATS - Eapp INF NHMeanburden 34.csv")
write.csv(output.summary.51, "stats output/STATS - Eapp INF NHMeanburden 51.csv")
write.csv(output.summary.all, "stats output/STATS - Eapp INF NHMeanburden all.csv")
