## --------------------- run_statistical_analysis
##
## Read in relevant data files and run brm analyses for each specified time window
##  Output summary (estimate & upr/lwr CIs) to summary data files 
##





## ----------------------------------------------------------- LOAD DATA 

#Read in relevant datafiles as generated by 'execute.parasite.function'
Ehung_hpol17 <- read.csv("output/Ehung_hpol17.csv", header = T)
Ehung_hpol34 <- read.csv("output/Ehung_hpol34.csv", header = T)
Ehung_hpol51 <- read.csv("output/Ehung_hpol51.csv", header = T)
Ehung_hpolall <- read.csv("output/Ehung_hpolall.csv", header = T)
Eapp_hpol17 <- read.csv("output/Eapp_hpol17.csv", header = T)
Eapp_hpol34 <- read.csv("output/Eapp_hpol34.csv", header = T)
Eapp_hpol51 <- read.csv("output/Eapp_hpol51.csv", header = T)
Eapp_hpolall <- read.csv("output/Eapp_hpolall.csv", header = T)

## ------------------------------------------------------ LOAD FUNCTIONS


source("funcs/model.run.R")
library(rstan)
library(bayesplot)
library(brms)
library(ggplot2)
library(reshape2)
library(rstanarm)
library(gtools)
library(tictoc)


## ----------------------------------------------------- SET PRIORS & CONDITIONS

Response.Parasite <- "E. hungaryensis" #Specify Ehung or Eapp as needed
Explanatory.Parasite <- "H. polygyrus"

prior <- c(prior_string("normal(0,10)", class = "b"))


## ------------------------------------------------------ RUN MODELS


var.names <- c("Prev_10", "Prev_14.1", "Prev_20", "Prev_22.4", "Prev_28.3", "Prev_30",
               "Prev_31.6", "Prev_36.1", "Prev_40", "Prev_50")

#Carry out analysis for each specified time window
tic()
model.data  <- Ehung_hpol17
model.data$response.var <- model.data$EhungInt
output.summary.17 <- model.run(model.data, var.names)

model.data  <- Ehung_hpol34
model.data$response.var <- model.data$EhungInt
output.summary.34 <- model.run(model.data, var.names)

model.data  <- Ehung_hpol51
model.data$response.var <- model.data$EhungInt
output.summary.51 <- model.run(model.data, var.names)

model.data  <- Ehung_hpolall
model.data$response.var <- model.data$EhungInt
output.summary.all <- model.run(model.data, var.names)
toc()

#Outout summary data for each timepoint
write.csv(output.summary.17, "output/Ehung_hpol17 stats.csv")
write.csv(output.summary.34, "output/Ehung_hpol34 stats.csv")
write.csv(output.summary.51, "output/Ehung_hpol51 stats.csv")
write.csv(output.summary.all, "output/Ehung_hpolall stats.csv")


